services:
  classes-service:
    container_name: classes-service
    build:
      context: ./apps/backend/classes-service
    environment:
      PORT: ${CLASSES_SERVICE_PORT}
      HOST: ${CLASSES_SERVICE_HOST}
    volumes:
      - ./apps/backend/classes-service:/usr/src/app
    command: sh -c "npm install && npm run start:dev"
  gateway-app:
    container_name: gateway
    build:
      context: ./apps/backend/gateway
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      PORT: ${BACKEND_PORT}
      CLASSES_SERVICE_NAME: ${CLASSES_SERVICE_NAME}
      CLASSES_SERVICE_PORT: ${CLASSES_SERVICE_PORT}
    volumes:
      - ./apps/backend/gateway:/usr/src/app
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - classes-service
  frontend-app:
    container_name: frontend
    build:
      context: ./apps/frontend
      dockerfile: ./Dockerfile.${MODE}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      FRONTEND_PORT: ${FRONTEND_PORT}
      NEXT_PUBLIC_BACKEND_URL: ${NEXT_PUBLIC_BACKEND_URL}
      BACKEND_URL: ${BACKEND_URL}
    volumes:
      - ./apps/frontend:/usr/src/app
    command: sh -c "npm install && npm run dev"
    depends_on:
      - gateway-app

volumes:
  mongo_data: {}
